### ISSUE TITLE
Why is it impossible to properly include a bind key stanza without Bind::Key dependency?

### ISSUE THREAD

**Issue by witchbutter** [theforeman/puppet-dhcp#125]
If this module is actually dependent on a Bind::Key resource from another module that dependency should be clearly stated.  If it isn't dependent the correct method needs to be in the README.md.  Both theforeman/dhcp and the foreman/dns need their READMEs updated badly.  Telling everyone to join the IRC channel for the Foreman is counterproductive.

The sections enable DDNS:
`ddns_updates => true,`
`ddns_domainname => $my_domain,`
`ddns_rev_domainname => $my_domain,`

But it can't properly function without additional steps because the dhcpd.conf.erb will never include the definition of the key.

Setting the option:
`dnsupdatekey => '/etc/dhcp/dynamic',`
Tells the config where to look for a separate stanza in a file that could have just been in dhcpd.conf

The contents of the file have to be in a format similar to this (where you set a secret appropriate for the algorithm of your choice and note that several algorithms available don't actually work):
`key dynamic {
  algorithm hmac-md5;
  secret "abcdefghijklmnopqrstuvwxyz";
}`

And setting the option:
`dnskeyname => 'dynamic',`
Add key dynamic to every pool so that it knows to refer to a key named 'dynamic' that you had created.

The actual key that DNS would use is a separate piece you would need setting up bind9 and using dnssec-keygen but which should have the same name when you cat the public key generated by dnssec-keygen.

I hope this helps save someone the awesome headache of trying to use this module.

**Comment by ekohl** [comment]
I think you're right. This is something we mostly do in https://github.com/theforeman/puppet-foreman_proxy but I must admit I haven't really used it myself. It could certainly use more documentation.

**Comment by ekohl** [comment]
After taking a closer look it appears this was part of the very first commit and hasn't been updated since. Typically we use https://github.com/theforeman/puppet-dns for our DNS needs (which IMHO should be called ```bind``` rather than ```dns```) but that only gained ```dns::key``` in https://github.com/theforeman/puppet-dns/commit/3703d83b507c4b7008e02986b2c4864f8f298e60 (26 days ago).

In short: you're looking at ancient code (2f1bbd2ba400514860f6af4f1955157789110766 is dated in 2012) which was then even older. PRs to the documentation/examples would be highly appreciated.
